import { Injectable } from '@angular/core';

/** Global JSZip instance provided by the library for file compression */
declare const JSZip: any;

/**
 * Service for exporting Compodoc templates as a ZIP file.
 * Uses the JSZip library to bundle multiple files and generate a download.
 */
@Injectable({
  providedIn: 'root'
})
export class ZipExportService {

  /**
   * Bundles the provided files into a ZIP archive and triggers a browser download.
   * Also includes a dynamically generated README.md with usage instructions.
   * @param files - Array of objects containing file 'path' and 'content'
   */
  exportTemplates(files: any[]) {
    const zip = new JSZip();

    // Add all template files to the ZIP
    files.forEach(file => {
      zip.file(file.path, file.content);
    });

    // Add a README with instructions
    const readme = this.generateReadme();
    zip.file('README.md', readme);

    // Generate and download the ZIP file
    zip.generateAsync({ type: 'blob' })
      .then((content: Blob) => {
        this.downloadBlob(content, 'compodoc-templates.zip');
      });
  }

  /**
   * Generates the content for the README.md file included in the export.
   * Provides instructions on how to use the custom templates with Compodoc.
   * @returns Markdown string for the README
   */
  private generateReadme(): string {
    return `# Compodoc Custom Templates

This ZIP file contains customized templates for Compodoc documentation generation.

## Contents

- **Templates** (\`.hbs\` files): Handlebars templates for generating documentation pages
- **Styles** (\`.css\` files): Stylesheets for customizing the appearance
- **Scripts** (\`.js\` files): JavaScript files for additional functionality

## Usage

1. Extract this ZIP file to a directory on your system
2. Use the \`--templates\` flag when running Compodoc to specify the path to your custom templates:

   \`\`\`bash
   compodoc -p tsconfig.json --templates ./path/to/custom/templates/
   \`\`\`

## Template Structure

- \`page.hbs\` - Main page template
- \`partials/\` - Directory containing partial templates
- \`styles/\` - Directory containing CSS files
- \`js/\` - Directory containing JavaScript files

## Customization Tips

1. **Templates**: Use Handlebars syntax to customize the HTML structure
2. **Styles**: Modify CSS to change colors, fonts, layout, etc.
3. **Scripts**: Add custom JavaScript functionality

## Backup

Always keep a backup of your original templates before making changes.

## Documentation

For more information about customizing Compodoc templates, visit:
https://compodoc.app/guides/template-customization.html

Generated by Compodoc Template Playground
`;
  }

  /**
   * Utility method to trigger a browser-level download of a Blob.
   * @param blob - The binary data to download
   * @param filename - The name to give the downloaded file
   */
  private downloadBlob(blob: Blob, filename: string) {
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.style.display = 'none';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
  }
}
