import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { environment } from '../../environments/environment';
import { Observable } from 'rxjs';

/**
 * Represents a workout or diet plan generated by the AI.
 */
export interface AiGeneratedPlan {
    /** The type of plan generated ('WORKOUT' for exercises or 'DIET' for meals) */
    type: "WORKOUT" | "DIET";
    /** User-friendly name for the plan (e.g., 'Mass Gain Phase 1') */
    name: string;
    /** Short summary of what the plan contains and its primary goals */
    description: string;
    /** List of days and their associated items (exercises or meals) */
    days: {
        /** Day of the week index (0 for Monday, 6 for Sunday) */
        dayOfWeek: number;
        /** Items included in this specific day (exercises or meals) */
        items: {
            /** Name of the exercise or meal component */
            name: string;
            /** Number of sets (Workout only) */
            sets?: number;
            /** Number of repetitions per set (Workout only) */
            reps?: number;
            /** Portion size or quantity (Diet only) */
            quantity?: string;
            /** Additional instructions, technical cues, or context */
            notes?: string;
        }[];
    }[];
}

/**
 * Standard response structure for AI chat interactions.
 */
export interface ChatResponse {
    /** Unique identifier for the chat session, used for thread persistence */
    sessionId: string;
    /** The actual response content from the AI model */
    response: {
        /** Textual explanation, greeting, or guidance from the AI assistant */
        message: string;
        /** Optional: a structured plan if one was requested or generated during the turn */
        plan?: AiGeneratedPlan;
    };
}

/**
 * Represents a historical or active chat session with the AI.
 */
export interface ChatSession {
    /** Unique session identifier in the database */
    id: string;
    /** Human-readable title for the session, often summarized from context */
    title: string | null;
    /** ISO date string of when the session was originally started */
    createdAt: string;
    /** History of messages exchanged in this session in chronological order */
    messages: {
        /** Role of the sender ('user' for the client or 'assistant' for the AI) */
        role: string;
        /** Content text of the message */
        content: string;
        /** ISO date string of when the message was sent */
        createdAt: string;
    }[];
}

/**
 * Service for interacting with the AI backend to generate plans and chat with users.
 * Supports session persistence and direct plan saving into user profiles.
 */
@Injectable({
    providedIn: 'root'
})
export class AiService {
    /** Injected HttpClient for AI API requests */
    private http = inject(HttpClient);
    /** Base API URL for AI operations */
    private apiUrl = `${environment.apiUrl}/ai`;

    /**
     * Sends a message to the AI and retrieves a response, potentially including a plan.
     * @param message - The user's prompt or question
     * @param sessionId - Optional: existing session ID to continue a conversation
     * @returns Observable emitting the chat response
     */
    sendMessage(message: string, sessionId?: string): Observable<ChatResponse> {
        return this.http.post<ChatResponse>(`${this.apiUrl}/chat`, { message, sessionId });
    }

    /**
     * Lists all chat sessions for the authenticated user.
     * @returns Observable emitting an array of chat sessions
     */
    getSessions(): Observable<ChatSession[]> {
        return this.http.get<ChatSession[]>(`${this.apiUrl}/sessions`);
    }

    /**
     * Saves a structured AI-generated plan into the user's records.
     * @param plan - The structured plan object to save
     * @returns Observable emitting the save result
     */
    savePlan(plan: AiGeneratedPlan): Observable<any> {
        return this.http.post<any>(`${this.apiUrl}/save-plan`, { plan });
    }

    /**
     * Deletes a chat session and its history.
     * @param sessionId - The ID of the session to delete
     * @returns Observable emitting the deletion result
     */
    deleteSession(sessionId: string): Observable<any> {
        return this.http.delete<any>(`${this.apiUrl}/sessions/${sessionId}`);
    }
}

