import { Injectable, inject } from '@angular/core';
import { Observable, from, throwError } from 'rxjs';
import { catchError, map } from 'rxjs/operators';
import { SupabaseService } from '../core/services/supabase.service';

/**
 * Represents a workout or diet plan generated by the AI.
 */
export interface AiGeneratedPlan {
    /** The type of plan generated ('WORKOUT' for exercises or 'DIET' for meals) */
    type: "WORKOUT" | "DIET";
    /** User-friendly name for the plan (e.g., 'Mass Gain Phase 1') */
    name: string;
    /** Short summary of what the plan contains and its primary goals */
    description: string;
    /** List of days and their associated items (exercises or meals) */
    days: {
        /** Day of the week index (0 for Monday, 6 for Sunday) */
        dayOfWeek: number;
        /** Items included in this specific day (exercises or meals) */
        items: {
            /** Name of the exercise or meal component */
            name: string;
            /** Number of sets (Workout only) */
            sets?: number;
            /** Number of repetitions per set (Workout only) */
            reps?: number;
            /** Portion size or quantity (Diet only) */
            quantity?: string;
            /** Additional instructions, technical cues, or context */
            notes?: string;
        }[];
    }[];
}

/**
 * Standard response structure for AI chat interactions.
 */
export interface ChatResponse {
    /** Unique identifier for the chat session, used for thread persistence */
    sessionId: string;
    /** The actual response content from the AI model */
    response: {
        /** Textual explanation, greeting, or guidance from the AI assistant */
        message: string;
        /** Optional: a structured plan if one was requested or generated during the turn */
        plan?: AiGeneratedPlan;
    };
}

/**
 * Represents a historical or active chat session with the AI.
 */
export interface ChatSession {
    /** Unique session identifier in the database */
    id: string;
    /** Human-readable title for the session, often summarized from context */
    title: string | null;
    /** ISO date string of when the session was originally started */
    createdAt: string;
    /** History of messages exchanged in this session in chronological order */
    messages: {
        /** Role of the sender ('user' for the client or 'assistant' for the AI) */
        role: string;
        /** Content text of the message */
        content: string;
        /** ISO date string of when the message was sent */
        createdAt: string;
    }[];
}

/**
 * Service for interacting with the AI backend to generate plans and chat with users.
 * Supports session persistence and direct plan saving into user profiles.
 */
@Injectable({
    providedIn: 'root'
})
export class AiService {
    private supabase = inject(SupabaseService).client;

    /**
     * Sends a message to the AI and retrieves a response, potentially including a plan.
     * @param message - The user's prompt or question
     * @param sessionId - Optional: existing session ID to continue a conversation
     * @returns Observable emitting the chat response
     */
    sendMessage(message: string, sessionId?: string): Observable<ChatResponse> {
        return from(
            this.supabase.functions.invoke('chat-ai', {
                body: { userMessage: message, sessionId }
            })
        ).pipe(
            map(({ data, error }) => {
                if (error) throw error;
                // Edge function devuelve { response: string, sessionId }
                return {
                    sessionId: data.sessionId,
                    response: { message: data.response }
                } as ChatResponse;
            }),
            catchError(err => throwError(() => new Error(err.message)))
        );
    }

    /**
     * Lists all chat sessions for the authenticated user.
     * @returns Observable emitting an array of chat sessions
     */
    getSessions(): Observable<ChatSession[]> {
        return from(
            this.supabase
                .from('AiChatSession')
                .select('id,title,createdAt, AiChatMessage(id,role,content,createdAt)')
                .order('createdAt', { ascending: false })
        ).pipe(
            map(({ data, error }) => {
                if (error) throw error;
                const rows = (data ?? []) as any[];
                return rows.map((s) => ({
                    id: s.id,
                    title: s.title,
                    createdAt: s.createdAt,
                    messages: (s.AiChatMessage ?? []).map((m: any) => ({
                        role: m.role,
                        content: m.content,
                        createdAt: m.createdAt,
                    })),
                })) as ChatSession[];
            }),
            catchError(err => throwError(() => new Error(err.message)))
        );
    }

    /**
     * Saves a structured AI-generated plan into the user's records.
     * @param plan - The structured plan object to save
     * @returns Observable emitting the save result
     */
    savePlan(plan: AiGeneratedPlan): Observable<any> {
        // Guardado de planes: por ahora lo dejamos como responsabilidad del cliente
        // (puedes persistirlo en tus tablas cuando definas el modelo).
        return throwError(() => new Error('savePlan no está implementado en modo Supabase-native todavía.'));
    }

    /**
     * Deletes a chat session and its history.
     * @param sessionId - The ID of the session to delete
     * @returns Observable emitting the deletion result
     */
    deleteSession(sessionId: string): Observable<any> {
        return from(this.supabase.from('AiChatSession').delete().eq('id', sessionId)).pipe(
            map(({ error }) => {
                if (error) throw error;
                return { ok: true };
            }),
            catchError(err => throwError(() => new Error(err.message)))
        );
    }
}

