#!/usr/bin/env node
/**
 * set-env.js
 *
 * Materializes `src/environments/environment.ts` and
 * `src/environments/environment.development.ts` from environment variables.
 *
 * Order of precedence for each required value:
 *   1. process.env (Vercel build injects the project's Environment Variables here)
 *   2. front/.env (local, gitignored)
 *   3. back/.env  (local, gitignored)
 *
 * Required values:
 *   SUPABASE_URL              (aliases: NEXT_PUBLIC_SUPABASE_URL)
 *   SUPABASE_KEY              (aliases: NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,
 *                                      NEXT_PUBLIC_SUPABASE_ANON_KEY,
 *                                      SUPABASE_ANON_KEY,
 *                                      SUPABASE_PUBLISHABLE_KEY)
 *   SUPABASE_FUNCTIONS_URL    (optional; derived as `${url}/functions/v1` when missing)
 *
 * If values are still missing after all fallbacks, the script exits with
 * status 1. This is intentional: failing the Vercel build is better than
 * shipping a bundle with placeholder URLs.
 */

const fs = require('fs');
const path = require('path');

const FRONT_ROOT = path.resolve(__dirname, '..');
const REPO_ROOT = path.resolve(FRONT_ROOT, '..');
const OUT_DIR = path.join(FRONT_ROOT, 'src', 'environments');

const URL_KEYS = ['NEXT_PUBLIC_SUPABASE_URL', 'SUPABASE_URL'];
const KEY_KEYS = [
  'NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY',
  'NEXT_PUBLIC_SUPABASE_ANON_KEY',
  'SUPABASE_PUBLISHABLE_KEY',
  'SUPABASE_ANON_KEY',
  'SUPABASE_KEY',
];
const FUNCTIONS_URL_KEYS = [
  'NEXT_PUBLIC_SUPABASE_FUNCTIONS_URL',
  'SUPABASE_FUNCTIONS_URL',
];

function parseDotenv(filePath) {
  if (!fs.existsSync(filePath)) return {};
  const raw = fs.readFileSync(filePath, 'utf8');
  const out = {};
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

const dotenvSources = [
  path.join(FRONT_ROOT, '.env'),
  path.join(REPO_ROOT, 'back', '.env'),
];

const dotenvMerged = dotenvSources.reduce((acc, file) => {
  const parsed = parseDotenv(file);
  return { ...parsed, ...acc };
}, {});

function resolve(keys) {
  for (const k of keys) {
    if (process.env[k] && process.env[k].trim()) return process.env[k].trim();
  }
  for (const k of keys) {
    if (dotenvMerged[k] && dotenvMerged[k].trim()) return dotenvMerged[k].trim();
  }
  return undefined;
}

const supabaseUrl = resolve(URL_KEYS);
const supabaseKey = resolve(KEY_KEYS);
let supabaseFunctionsUrl = resolve(FUNCTIONS_URL_KEYS);

const missing = [];
if (!supabaseUrl) missing.push('SUPABASE_URL (or NEXT_PUBLIC_SUPABASE_URL)');
if (!supabaseKey)
  missing.push(
    'SUPABASE_KEY (or NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY / SUPABASE_ANON_KEY)'
  );

if (missing.length) {
  console.error('\n[set-env] ERROR: missing required environment variables:');
  for (const m of missing) console.error('  - ' + m);
  console.error(
    '\nProvide them via Vercel Project Settings > Environment Variables, ' +
      'or in a local front/.env or back/.env file.\n'
  );
  process.exit(1);
}

if (!supabaseFunctionsUrl) {
  supabaseFunctionsUrl = supabaseUrl.replace(/\/+$/, '') + '/functions/v1';
}

function render(production) {
  return (
    '/**\n' +
    ' * ' +
    (production ? 'Production' : 'Development') +
    ' environment configuration.\n' +
    ' *\n' +
    ' * AUTO-GENERATED by scripts/set-env.js at build time.\n' +
    ' * Do not edit by hand; do not commit. See front/.gitignore.\n' +
    ' */\n' +
    'export const environment = {\n' +
    '  production: ' +
    String(production) +
    ',\n' +
    '  supabaseUrl: ' +
    JSON.stringify(supabaseUrl) +
    ',\n' +
    '  supabaseKey: ' +
    JSON.stringify(supabaseKey) +
    ',\n' +
    '  supabaseFunctionsUrl: ' +
    JSON.stringify(supabaseFunctionsUrl) +
    ',\n' +
    '};\n'
  );
}

fs.mkdirSync(OUT_DIR, { recursive: true });
const prodFile = path.join(OUT_DIR, 'environment.ts');
const devFile = path.join(OUT_DIR, 'environment.development.ts');
fs.writeFileSync(prodFile, render(true), 'utf8');
fs.writeFileSync(devFile, render(false), 'utf8');

function mask(v) {
  if (!v) return v;
  if (v.length <= 8) return '*'.repeat(v.length);
  return v.slice(0, 4) + '…' + v.slice(-4);
}

console.log('[set-env] Wrote ' + path.relative(FRONT_ROOT, prodFile));
console.log('[set-env] Wrote ' + path.relative(FRONT_ROOT, devFile));
console.log('[set-env]   supabaseUrl          = ' + supabaseUrl);
console.log('[set-env]   supabaseKey          = ' + mask(supabaseKey));
console.log('[set-env]   supabaseFunctionsUrl = ' + supabaseFunctionsUrl);
